### ISSUE TITLE
Exception while loading the app

### ISSUE THREAD

**Issue by smuralee** [smuralee/spring-batch-quartz-admin#3]
Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [errorChannel] with key 'errorChannel'; nested exception is org.springframework.jmx.export.MBeanExportException: Could not create ModelMBean for managed resource [errorChannel] with key 'errorChannel'; nested exception is java.lang.IllegalArgumentException: MetadataMBeanInfoAssembler does not support JDK dynamic proxies - export the target beans directly or use CGLIB proxies instead

**Comment by smuralee** [comment]
Resolved.

Root cause: The dependencies for Spring 4 was conflicting with the Spring 3.2.9 used by the spring-batch-admin-manager and spring-batch-admin-resources 1.3.1.RELEASE

**Comment by sivakuna-aap** [comment]
@smuralee what exactly you did to resolve this? It would be great if you can mention the changes you did either in pom or code.

**Comment by smuralee** [comment]
@sivakuna-aap the issue was due to the inclusion of Spring 4 dependency. The batch admin projects are internally still using Spring 3, but I had upgraded the Spring version in my pom.xml. This caused a conflict and the exception occurred.

You can check the updates to pom.xml in the [history](https://github.com/smuralee/spring-batch-quartz-admin/commit/700ae93cb182e071b1ffb5b4f72de5eb30e1223c#diff-600376dffeb79835ede4a0b285078036)
