### ISSUE TITLE
Cannot locate datasouce.

### ISSUE THREAD

**Issue by nikhilenmudi** [smuralee/spring-batch-quartz-admin#4]
Hi,

I cloned your project and now I am trying to add my custom jobs that i have in a separate spring batch boot application to this cloned app. However i cannot locate the dataSource bean or transactionManager bean. I am using Hibernate JPA too. can you please let me know how to modify my datasource and transaction manager?

**Comment by smuralee** [comment]
There is no separate data source configured. I am using the in-memory database which  has the scripts invoked by the spring batch admin during boot. Please share the error you encountered.

**Comment by nikhilenmudi** [comment]
Thanks, I resolved it myself, it took me a while to understand where it is getting datasource properties from and other resources. Apparently it all comes from the jar files unless we override them.
