### ISSUE TITLE
Upgrade to spring 4.x and test classes.

### ISSUE THREAD

**Issue by nikhilenmudi** [smuralee/spring-batch-quartz-admin#5]
I upgraded the spring version to 4.3.8 but now when i run the project the server crashes with a No Class Def found for EventListener. Can you upgrade the project to use 4.3.8 and include a sample test class that can test one of the services?

**Comment by smuralee** [comment]
The project is using spring-batch-admin-manager which is version 1.3.1. This uses the Spring core - 3.2.9. The spring team is yet to provide an updated version of the spring-batch-admin-manager. For my project, we were using Spring 3.x, hence the application version worked for me.

Feel free to fork the repo and try upgrading the version
